# Generated by Django 5.0.6 on 2024-05-30 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='account',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
