# Generated by Django 5.0.6 on 2024-05-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_remove_userdata_id_alter_userdata_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='id',
            field=models.BigAutoField(auto_created=True, default=9903, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdata',
            name='account',
            field=models.CharField(max_length=20),
        ),
    ]
